
name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install MAUI Workloads
      run: dotnet workload  install maui-android
    - name: Install .Net maui Windows
      run: dotnet workload install maui-windows
    
    - name: Restore dependencies
      run: dotnet restore
  
    - name: Build
      run: dotnet build --no-restore
    - name: Deploy Windows App Without Signing
      run: dotnet publish -f net6.0-windows10.0.19041.0 -c Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal
